FROM golang:1.17 as builder

RUN mkdir /nats
COPY . /nats
WORKDIR /nats/cmd/reqrep/receiver
RUN CGO_ENABLED=0 GOOS=linux go build .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /nats/cmd/reqrep/receiver ./
CMD ["./receiver"]
