version: "3"
services:
  sender:
    build:
      context: .
      dockerfile: Dockerfile_publisher
    environment:
      - PUBLISHER_NATS_ADDRESS=nats-server:4222
      - PUBLISHER_TOKEN_LIST=eagle,worm,spider,raindeer
    depends_on:
      - nats-server
    restart: unless-stopped
  receiver_1:
    build:
      context: .
      dockerfile: Dockerfile_qgroup_subscriber
    environment:
      - SUBSCRIBER_NATS_ADDRESS=nats-server:4222
      - SUBSCRIBER_SUBJECT=spider.>
      - SUBSCRIBER_QUEUE_GROUP=spider_busters
    depends_on:
      - nats-server
    restart: unless-stopped
  receiver_2:
    build:
      context: .
      dockerfile: Dockerfile_qgroup_subscriber
    environment:
      - SUBSCRIBER_NATS_ADDRESS=nats-server:4222
      - SUBSCRIBER_SUBJECT=spider.>
      - SUBSCRIBER_QUEUE_GROUP=spider_busters
    depends_on:
      - nats-server
    restart: unless-stopped
  nats-server:
    image: "nats:alpine"
    restart: unless-stopped
    hostname: "nats-server"
    ports:
      - "4222:4222"
