version: "3"
services:
  sender:
    build:
      context: .
      dockerfile: Dockerfile_sender
    environment:
      - SENDER_NATS_ADDRESS=nats-server:4222
      - SENDER_SUBJECT=int_value
      - SENDER_REPLY_SUBJECT=reply_value
    depends_on:
      - nats-server
    restart: unless-stopped
  receiver_1:
    build:
      context: .
      dockerfile: Dockerfile_receiver
    environment:
      - RECEIVER_NATS_ADDRESS=nats-server:4222
      - RECEIVER_SUBJECT=int_value
    depends_on:
      - nats-server
    restart: unless-stopped
  receiver_2:
    build:
      context: .
      dockerfile: Dockerfile_receiver
    environment:
      - RECEIVER_NATS_ADDRESS=nats-server:4222
      - RECEIVER_SUBJECT=not-in-use
    depends_on:
      - nats-server
    restart: unless-stopped
  nats-server:
    image: "nats:alpine"
    restart: unless-stopped
    hostname: "nats-server"
    ports:
      - "4222:4222"
