FROM golang:1.17 as builder

RUN mkdir /pubsub
COPY . /pubsub
WORKDIR /pubsub/cmd/publisher
RUN CGO_ENABLED=0 GOOS=linux go build .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /pubsub/cmd/publisher/publisher ./
CMD ["./publisher"]
