FROM golang:1.17 as builder

RUN mkdir /nssq
COPY . /nsq
WORKDIR /nsq/cmd/producer
RUN CGO_ENABLED=0 GOOS=linux go build .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /nsq/cmd/producer/producer ./
CMD ["./producer"]
