FROM golang:1.17 as builder

RUN mkdir /nsq
COPY . /nsq
WORKDIR /nsq/cmd/consumer
RUN CGO_ENABLED=0 GOOS=linux go build .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /nsq/cmd/consumer/consumer ./
CMD ["./consumer"]
